### ISSUE TITLE
Review Needed

### ISSUE THREAD

**Issue by bastienjacoud** [PolytechLyon/isi3-tp1-graph-jacoud_remond#1]

**Comment by Slashgear** [comment]
- [ ] 💡  il est possible d'encore plus factoriser les algorithmes de parcours

- [ ] la classe Node ne surcharge pas la méthode `hashcode` quel est l'impact ?

- [ ] préfixer les variables privée par `_` c'est une bad practice, maintenant nos IDE savent maintenant bien nous indiquer si l'attribut est privé et pas public
https://github.com/PolytechLyon/isi3-tp1-graph-jacoud_remond/blob/56a56eb66897ff2346012d0750f188b630f15bce/src/main/java/graph/UndirectedGraph.java#L12

- [ ] ici le type pourrait être IGraph, pourquoi ? 
https://github.com/PolytechLyon/isi3-tp1-graph-jacoud_remond/blob/56a56eb66897ff2346012d0750f188b630f15bce/src/main/java/graph/UndirectedGraph.java#L12

- 👍 le rapport

**Comment by bastienjacoud** [comment]
Bonjour, 
Suite à votre commentaire, j'ai réalisé les modifications nécessaire au niveau du code. 
Les algorithmes de parcours ont été factorisé afin qu'une seule ligne ne soit changée suivant le parcours effectué. 
De plus, j'ai surchargé la méthode hashcode(), ce qui permet d'utiliser la méthode equals() surchargée comme elle a été définie. Pour cela, j'ai utilisé la méthode hash() de Objetcs. 
Les "_" devant les paramètres de classe ont été modifiés. 
Le type IGraph a été lui aussi modifié. IGraph étant une interface de plus haut niveau, il est préférable de déclarer un type de plus haut niveau dans notre classe, pour améliorer l’adaptabilité de notre code.
Bien cordialement, 
Bastien Jacoud
